# Dependabot configuration
#
# See docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
    reviewers:
      - "PANTHEONtech/cdnf"
    groups:
      github-deps:
        patterns:
          - "*"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
    reviewers:
      - "PANTHEONtech/cdnf"
    groups:
      go-deps:
        patterns:
          - "*"

