// Code generated by adapter-generator. DO NOT EDIT.

package adapter

import (
	. "go.ligato.io/vpp-agent/v3/plugins/kvscheduler/api"
	"go.pantheon.tech/stonework/proto/nat64"
	"google.golang.org/protobuf/proto"
)

////////// type-safe key-value pair with metadata //////////

type NAT64IPv6PrefixKVWithMetadata struct {
	Key      string
	Value    *nat64.Nat64IPv6Prefix
	Metadata interface{}
	Origin   ValueOrigin
}

////////// type-safe Descriptor structure //////////

type NAT64IPv6PrefixDescriptor struct {
	Name                 string
	KeySelector          KeySelector
	ValueTypeName        string
	KeyLabel             func(key string) string
	ValueComparator      func(key string, oldValue, newValue *nat64.Nat64IPv6Prefix) bool
	NBKeyPrefix          string
	WithMetadata         bool
	MetadataMapFactory   MetadataMapFactory
	Validate             func(key string, value *nat64.Nat64IPv6Prefix) error
	Create               func(key string, value *nat64.Nat64IPv6Prefix) (metadata interface{}, err error)
	Delete               func(key string, value *nat64.Nat64IPv6Prefix, metadata interface{}) error
	Update               func(key string, oldValue, newValue *nat64.Nat64IPv6Prefix, oldMetadata interface{}) (newMetadata interface{}, err error)
	UpdateWithRecreate   func(key string, oldValue, newValue *nat64.Nat64IPv6Prefix, metadata interface{}) bool
	Retrieve             func(correlate []NAT64IPv6PrefixKVWithMetadata) ([]NAT64IPv6PrefixKVWithMetadata, error)
	IsRetriableFailure   func(err error) bool
	DerivedValues        func(key string, value *nat64.Nat64IPv6Prefix) []KeyValuePair
	Dependencies         func(key string, value *nat64.Nat64IPv6Prefix) []Dependency
	RetrieveDependencies []string /* descriptor name */
}

////////// Descriptor adapter //////////

type NAT64IPv6PrefixDescriptorAdapter struct {
	descriptor *NAT64IPv6PrefixDescriptor
}

func NewNAT64IPv6PrefixDescriptor(typedDescriptor *NAT64IPv6PrefixDescriptor) *KVDescriptor {
	adapter := &NAT64IPv6PrefixDescriptorAdapter{descriptor: typedDescriptor}
	descriptor := &KVDescriptor{
		Name:                 typedDescriptor.Name,
		KeySelector:          typedDescriptor.KeySelector,
		ValueTypeName:        typedDescriptor.ValueTypeName,
		KeyLabel:             typedDescriptor.KeyLabel,
		NBKeyPrefix:          typedDescriptor.NBKeyPrefix,
		WithMetadata:         typedDescriptor.WithMetadata,
		MetadataMapFactory:   typedDescriptor.MetadataMapFactory,
		IsRetriableFailure:   typedDescriptor.IsRetriableFailure,
		RetrieveDependencies: typedDescriptor.RetrieveDependencies,
	}
	if typedDescriptor.ValueComparator != nil {
		descriptor.ValueComparator = adapter.ValueComparator
	}
	if typedDescriptor.Validate != nil {
		descriptor.Validate = adapter.Validate
	}
	if typedDescriptor.Create != nil {
		descriptor.Create = adapter.Create
	}
	if typedDescriptor.Delete != nil {
		descriptor.Delete = adapter.Delete
	}
	if typedDescriptor.Update != nil {
		descriptor.Update = adapter.Update
	}
	if typedDescriptor.UpdateWithRecreate != nil {
		descriptor.UpdateWithRecreate = adapter.UpdateWithRecreate
	}
	if typedDescriptor.Retrieve != nil {
		descriptor.Retrieve = adapter.Retrieve
	}
	if typedDescriptor.Dependencies != nil {
		descriptor.Dependencies = adapter.Dependencies
	}
	if typedDescriptor.DerivedValues != nil {
		descriptor.DerivedValues = adapter.DerivedValues
	}
	return descriptor
}

func (da *NAT64IPv6PrefixDescriptorAdapter) ValueComparator(key string, oldValue, newValue proto.Message) bool {
	typedOldValue, err1 := castNAT64IPv6PrefixValue(key, oldValue)
	typedNewValue, err2 := castNAT64IPv6PrefixValue(key, newValue)
	if err1 != nil || err2 != nil {
		return false
	}
	return da.descriptor.ValueComparator(key, typedOldValue, typedNewValue)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) Validate(key string, value proto.Message) (err error) {
	typedValue, err := castNAT64IPv6PrefixValue(key, value)
	if err != nil {
		return err
	}
	return da.descriptor.Validate(key, typedValue)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) Create(key string, value proto.Message) (metadata Metadata, err error) {
	typedValue, err := castNAT64IPv6PrefixValue(key, value)
	if err != nil {
		return nil, err
	}
	return da.descriptor.Create(key, typedValue)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) Update(key string, oldValue, newValue proto.Message, oldMetadata Metadata) (newMetadata Metadata, err error) {
	oldTypedValue, err := castNAT64IPv6PrefixValue(key, oldValue)
	if err != nil {
		return nil, err
	}
	newTypedValue, err := castNAT64IPv6PrefixValue(key, newValue)
	if err != nil {
		return nil, err
	}
	typedOldMetadata, err := castNAT64IPv6PrefixMetadata(key, oldMetadata)
	if err != nil {
		return nil, err
	}
	return da.descriptor.Update(key, oldTypedValue, newTypedValue, typedOldMetadata)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) Delete(key string, value proto.Message, metadata Metadata) error {
	typedValue, err := castNAT64IPv6PrefixValue(key, value)
	if err != nil {
		return err
	}
	typedMetadata, err := castNAT64IPv6PrefixMetadata(key, metadata)
	if err != nil {
		return err
	}
	return da.descriptor.Delete(key, typedValue, typedMetadata)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) UpdateWithRecreate(key string, oldValue, newValue proto.Message, metadata Metadata) bool {
	oldTypedValue, err := castNAT64IPv6PrefixValue(key, oldValue)
	if err != nil {
		return true
	}
	newTypedValue, err := castNAT64IPv6PrefixValue(key, newValue)
	if err != nil {
		return true
	}
	typedMetadata, err := castNAT64IPv6PrefixMetadata(key, metadata)
	if err != nil {
		return true
	}
	return da.descriptor.UpdateWithRecreate(key, oldTypedValue, newTypedValue, typedMetadata)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) Retrieve(correlate []KVWithMetadata) ([]KVWithMetadata, error) {
	var correlateWithType []NAT64IPv6PrefixKVWithMetadata
	for _, kvpair := range correlate {
		typedValue, err := castNAT64IPv6PrefixValue(kvpair.Key, kvpair.Value)
		if err != nil {
			continue
		}
		typedMetadata, err := castNAT64IPv6PrefixMetadata(kvpair.Key, kvpair.Metadata)
		if err != nil {
			continue
		}
		correlateWithType = append(correlateWithType,
			NAT64IPv6PrefixKVWithMetadata{
				Key:      kvpair.Key,
				Value:    typedValue,
				Metadata: typedMetadata,
				Origin:   kvpair.Origin,
			})
	}

	typedValues, err := da.descriptor.Retrieve(correlateWithType)
	if err != nil {
		return nil, err
	}
	var values []KVWithMetadata
	for _, typedKVWithMetadata := range typedValues {
		kvWithMetadata := KVWithMetadata{
			Key:      typedKVWithMetadata.Key,
			Metadata: typedKVWithMetadata.Metadata,
			Origin:   typedKVWithMetadata.Origin,
		}
		kvWithMetadata.Value = typedKVWithMetadata.Value
		values = append(values, kvWithMetadata)
	}
	return values, err
}

func (da *NAT64IPv6PrefixDescriptorAdapter) DerivedValues(key string, value proto.Message) []KeyValuePair {
	typedValue, err := castNAT64IPv6PrefixValue(key, value)
	if err != nil {
		return nil
	}
	return da.descriptor.DerivedValues(key, typedValue)
}

func (da *NAT64IPv6PrefixDescriptorAdapter) Dependencies(key string, value proto.Message) []Dependency {
	typedValue, err := castNAT64IPv6PrefixValue(key, value)
	if err != nil {
		return nil
	}
	return da.descriptor.Dependencies(key, typedValue)
}

////////// Helper methods //////////

func castNAT64IPv6PrefixValue(key string, value proto.Message) (*nat64.Nat64IPv6Prefix, error) {
	typedValue, ok := value.(*nat64.Nat64IPv6Prefix)
	if !ok {
		return nil, ErrInvalidValueType(key, value)
	}
	return typedValue, nil
}

func castNAT64IPv6PrefixMetadata(key string, metadata Metadata) (interface{}, error) {
	if metadata == nil {
		return nil, nil
	}
	typedMetadata, ok := metadata.(interface{})
	if !ok {
		return nil, ErrInvalidMetadataType(key)
	}
	return typedMetadata, nil
}
