// SPDX-License-Identifier: Apache-2.0

// Copyright 2021 PANTHEON.tech
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: abx/abx.proto

package vpp_abx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ACL based xconnect
type ABX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ABX index (unique identifier)
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Name of the associated access list
	AclName string `protobuf:"bytes,2,opt,name=acl_name,json=aclName,proto3" json:"acl_name,omitempty"`
	// Name of outgoing interface
	OutputInterface string `protobuf:"bytes,3,opt,name=output_interface,json=outputInterface,proto3" json:"output_interface,omitempty"`
	// Rewrite destination mac address
	DstMac             string                   `protobuf:"bytes,4,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`
	AttachedInterfaces []*ABX_AttachedInterface `protobuf:"bytes,5,rep,name=attached_interfaces,json=attachedInterfaces,proto3" json:"attached_interfaces,omitempty"`
}

func (x *ABX) Reset() {
	*x = ABX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abx_abx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ABX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABX) ProtoMessage() {}

func (x *ABX) ProtoReflect() protoreflect.Message {
	mi := &file_abx_abx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABX.ProtoReflect.Descriptor instead.
func (*ABX) Descriptor() ([]byte, []int) {
	return file_abx_abx_proto_rawDescGZIP(), []int{0}
}

func (x *ABX) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ABX) GetAclName() string {
	if x != nil {
		return x.AclName
	}
	return ""
}

func (x *ABX) GetOutputInterface() string {
	if x != nil {
		return x.OutputInterface
	}
	return ""
}

func (x *ABX) GetDstMac() string {
	if x != nil {
		return x.DstMac
	}
	return ""
}

func (x *ABX) GetAttachedInterfaces() []*ABX_AttachedInterface {
	if x != nil {
		return x.AttachedInterfaces
	}
	return nil
}

// List of interfaces attached to the ABX
type ABX_AttachedInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputInterface string `protobuf:"bytes,1,opt,name=input_interface,json=inputInterface,proto3" json:"input_interface,omitempty"`
	Priority       uint32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *ABX_AttachedInterface) Reset() {
	*x = ABX_AttachedInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abx_abx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ABX_AttachedInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABX_AttachedInterface) ProtoMessage() {}

func (x *ABX_AttachedInterface) ProtoReflect() protoreflect.Message {
	mi := &file_abx_abx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABX_AttachedInterface.ProtoReflect.Descriptor instead.
func (*ABX_AttachedInterface) Descriptor() ([]byte, []int) {
	return file_abx_abx_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ABX_AttachedInterface) GetInputInterface() string {
	if x != nil {
		return x.InputInterface
	}
	return ""
}

func (x *ABX_AttachedInterface) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_abx_abx_proto protoreflect.FileDescriptor

var file_abx_abx_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x62, 0x78, 0x2f, 0x61, 0x62, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x76, 0x70, 0x70, 0x2e, 0x61, 0x62, 0x78, 0x22, 0xa5, 0x02, 0x0a, 0x03, 0x41, 0x42, 0x58,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x64, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x73, 0x74, 0x4d, 0x61, 0x63, 0x12, 0x4f, 0x0a, 0x13, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x70, 0x70, 0x2e, 0x61, 0x62, 0x78, 0x2e, 0x41, 0x42, 0x58,
	0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x52, 0x12, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x58, 0x0a, 0x11, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x6f, 0x2e, 0x70, 0x61, 0x6e, 0x74, 0x68, 0x65, 0x6f, 0x6e, 0x2e,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x62, 0x78, 0x3b, 0x76, 0x70, 0x70, 0x5f, 0x61, 0x62, 0x78,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_abx_abx_proto_rawDescOnce sync.Once
	file_abx_abx_proto_rawDescData = file_abx_abx_proto_rawDesc
)

func file_abx_abx_proto_rawDescGZIP() []byte {
	file_abx_abx_proto_rawDescOnce.Do(func() {
		file_abx_abx_proto_rawDescData = protoimpl.X.CompressGZIP(file_abx_abx_proto_rawDescData)
	})
	return file_abx_abx_proto_rawDescData
}

var file_abx_abx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_abx_abx_proto_goTypes = []interface{}{
	(*ABX)(nil),                   // 0: vpp.abx.ABX
	(*ABX_AttachedInterface)(nil), // 1: vpp.abx.ABX.AttachedInterface
}
var file_abx_abx_proto_depIdxs = []int32{
	1, // 0: vpp.abx.ABX.attached_interfaces:type_name -> vpp.abx.ABX.AttachedInterface
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_abx_abx_proto_init() }
func file_abx_abx_proto_init() {
	if File_abx_abx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_abx_abx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ABX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abx_abx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ABX_AttachedInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_abx_abx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abx_abx_proto_goTypes,
		DependencyIndexes: file_abx_abx_proto_depIdxs,
		MessageInfos:      file_abx_abx_proto_msgTypes,
	}.Build()
	File_abx_abx_proto = out.File
	file_abx_abx_proto_rawDesc = nil
	file_abx_abx_proto_goTypes = nil
	file_abx_abx_proto_depIdxs = nil
}
