{
 "title": "VPP telemetry",
 "description": "Metrics retrieved from telemetry plugin",
 "tags": [ "vpp" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "agent", "query": { "query": "label_values(agent)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ligato_ifplugin_operational_state{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ligato_ifplugin_admin_state{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_rx_bytes{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_tx_bytes{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_rx_packets{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_tx_packets{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_rx_errors{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_tx_errors{name!=\"local0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vpp_interfaces_rx_miss{name!=\"local0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - ligato_process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vpp_interfaces_rx_bytes{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - RX bytes"
    },
    {
     "expr": "rate(vpp_interfaces_tx_bytes{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - TX bytes"
    },
    {
     "expr": "rate(vpp_interfaces_rx_packets{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - RX packets"
    },
    {
     "expr": "rate(vpp_interfaces_tx_packets{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - TX packets"
    },
    {
     "expr": "rate(vpp_interfaces_rx_errors{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - RX errors"
    },
    {
     "expr": "rate(vpp_interfaces_tx_errors{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - TX errors"
    },
    {
     "expr": "rate(vpp_interfaces_drops{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - drops"
    },
    {
     "expr": "rate(vpp_interfaces_punts{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - punts"
    },
    {
     "expr": "rate(vpp_interfaces_rx_miss{agent=\"$agent\", name!=\"local0\"}[10s])",
     "legendFormat": "{{name}} - RX miss"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vpp_memory_used{agent=\"$agent\"}/vpp_memory_total{agent=\"$agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ligato_process_cpu_seconds_total[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Counters",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "vpp_nodes_counter{agent=\"$agent\"}",
     "legendFormat": "{{item}}: {{reason}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "vpp_runtime_calls{job=\"vpp\", agent=\"$agent\"}+0\n\n",
     "legendFormat": "{{item}} calls"
    },
    {
     "expr": "vpp_runtime_vectors{agent=\"$agent\"}+0",
     "legendFormat": "{{item}} vectors"
    },
    {
     "expr": "vpp_runtime_suspends{agent=\"$agent\"}+0",
     "legendFormat": "{{item}} suspends"
    },
    {
     "expr": "vpp_runtime_clocks{agent=\"$agent\"}+0",
     "legendFormat": "{{item}} clocks"
    },
    {
     "expr": "vpp_runtime_vectors_per_call{agent=\"$agent\"}+0",
     "legendFormat": "{{item}} vectors/call"
    }
   ]
  },
  {
   "title": "Interface state (operational)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ligato_ifplugin_operational_state{name!=\"local0\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vpp_buffers_size{agent=\"$agent\"}",
     "legendFormat": "{{item}} ({{threadID}}) - size"
    },
    {
     "expr": "vpp_buffers_alloc{agent=\"$agent\"}",
     "legendFormat": "{{item}} ({{threadID}}) - alloc"
    },
    {
     "expr": "vpp_buffers_free{agent=\"$agent\"}",
     "legendFormat": "{{item}} ({{threadID}}) - free"
    },
    {
     "expr": "vpp_buffers_num_alloc{agent=\"$agent\"}",
     "legendFormat": "{{item}} ({{threadID}}) - num allocs"
    },
    {
     "expr": "vpp_buffers_num_free{agent=\"$agent\"}",
     "legendFormat": "{{item}} ({{threadID}}) - num free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vpp_memory_used{agent=\"$agent\"}",
     "legendFormat": "used [{{threadID}}]"
    },
    {
     "expr": "vpp_memory_reclaimed{agent=\"$agent\"}",
     "legendFormat": "reclaimed [{{threadID}}]"
    },
    {
     "expr": "vpp_memory_free{agent=\"$agent\"}",
     "legendFormat": "free [{{threadID}}]"
    }
   ]
  }
 ]
}