apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  user:
  database:
  basicAuth: false
  basicAuthUser:
  withCredentials: false
  isDefault: true
  jsonData:
    httpMethod: POST
  version: 2
  editable: true
