# Interval of data read procedure from the vpp. Default value is 30 seconds.
polling-interval: 30s

# If set to true, telemetry plugin is disabled.
disabled: false

# If set to true, prometheus in telemetry plugin is disabled.
prometheus-disabled: false

# Skip collecting some of the metrics.
# 	runtime, memory, buffers, nodes, interfaces
#skipped: [nodes]
