# SPDX-License-Identifier: Apache-2.0

# Copyright 2022 PANTHEON.tech
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.3'

volumes:
  runtime_data: {}

services:
  stonework:
    image: "ghcr.io/pantheontech/stonework:22.10"
    privileged: true
    pid: "host"
    environment:
      INITIAL_LOGLVL: "debug"
      MICROSERVICE_LABEL: "stonework"
      ETCD_CONFIG: ""
    ports:
      - "9111:9111"
      - "9191:9191"
    volumes:
      - runtime_data:/run/stonework
      - /sys/bus/pci:/sys/bus/pci
      - /dev:/dev
      - /run/docker.sock:/run/docker.sock
      - ./vpp-startup.conf:/etc/vpp/vpp.conf
      - ./config:/etc/stonework/config
